pkg load symbolic
clear
disp('Perez Fraguela, Eduardo(2.3).')
disp(' ')
disp(' ')
disp('Exercicio numero 1.')
disp('Apartado a.')
syms x; f(x) = (x)^2/(x-4)
disp('Calculamos os puntos onde a funcion anulase:')
solve(x-4==0), c = ans(1)
disp('Calculamos os limites:')
limit(f(x),x,-inf)
limit(f(x),x,inf)
disp('Non hai asintotas horizontales')
limit(f(x),x,c, 'left')
limit(f(x),x,c, 'right')
av = c 
disp('Hai unha asintota vertical no punto onde se anula a funcion.')
m = limit((x)^2/(x^2-4*x), x, inf)
n = limit((x)^2/(x-4)-x, x, inf)
ao = m*x + n
disp('Hai unha asintota oblicua.')
pause(5)
disp(' ')
disp('Apartado b.')
disp('**Grafico figure(1)**')
figure(1)
ezplot(f(x),[0,5])
hold on
plot([4,4],[-100,100], 'r --')
ezplot(ao,[0,5])
plot([0,0],[-100,100], 'k')
plot([0,5],[0,0], 'k')
text(3.6,40,'av = 4')
axis([0,5,-70,70])
text(2.5,12,'ao = x + 4')
title('Funcion apartado b.')
xlabel('Eixe OX')
ylabel('Eixe OY')
grid 
hold off
pause(5)
disp(' ')
disp('Apartado c.')
diff(f(x))
z(x) = diff(f(x));
solve(z(x)==0); x1=ans(1),x2=ans(2)
disp('Unha vez obtidos os extremos relativos, comprobamos o crecemento e decrecemento os lados dos extremos.')
z(x)= diff(f(x))
z1 = double(x1);
z2 = double(x2);
z(-1)
disp('Positivo para x<0')
z(1)
disp('Negativo para 0<x<4')
z(5)
disp('Negativo para 4<x<8')
z(10)
disp('Positivo para x<8')
fprintf('f(x) creciente de (-inf , %f) U (%f , +inf) e decrecente de (%f , 4) U (4 , %f).\n' , z1, z1, z2,z2)
fprintf('Polo tanto %f e un maximo e %f e un minimo.\n',z1,z2)
pause(15)
disp(' ')
disp(' ')
disp(' ')
disp('Exercicio 2.')
disp('Parte 1.')
syms x; i(x)=x*log(x);
a = int(i(x),x,0,1)
I(x) = int(i(x), x)
A = double(I(1)-limit(I(x),x,0,'right'))
pause(5)
disp('Parte 2.')
i(x)=x*log(x)
figure(2)
ezplot(i(x), [0,4])
hold on
plot([2,2],[-5,20], 'r --')
plot([0,0],[-5,20], 'r --')
plot([0,6],[0,0], 'k')
title('Area de i(x)')
hold off
int(i(x),x)
I(x)=int(i(x),x,0,2);
A = double(I(x));
fprintf('A area da funcion entre 0 e 2 e %f.\n' , A)
